### PR TITLE
Add I/O wiring harness

### PR DESCRIPTION
**Pull request by mdavidsaver**
Document I/O wiring harness.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
mps-wiring

**Comment by Trentronix** [comment]
Wiring to DB9 connectors looks good.
Here is the loopback test cable...
image

**Comment by sjstein** [comment]
The above wiring diagram seems to have pin 1 on the wrong side for J1 - referring to this [photo ](https://github.com/osprey-dcs/pmod-mps-io/blob/main/mps-io-conn.jpg )as reference

**Comment by mdavidsaver** [comment]
@sjstein This was corrected by https://github.com/osprey-dcs/pmod-mps-io/commit/a2288e9d4aaac9e7d9a01d36a92b569348715b04

Are you able to pull down and open `io-cable/io-cable.kicad_pro` with kicad?

**Comment by sjstein** [comment]
I don't use Kicad - but as long as the wiring diagram here is correct, I'll follow that for the assembly until the official documentation is updated

**Pull request closed without merging**
